on: [workflow_dispatch]

name: Render Report

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
          
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::viridis
               any::ggthemes
               any::htmltools
               any::tidyverse
               any::ggmap
               any::tidycensus
               any::plotly
               any::leaflet
               any::osmdata
               any::tigris
               any::sf
               any::flexdashboard
               any::shiny
               any::jsonlite
               any::purrr
               any::knitr
               any::rmarkdown
               any::dplyr
               any::tidyr
               any::ggplot2
               any::lubridate
               any::googleway
               any::purrr
               any::leaflet
               any::gepaf
               
      - name: Render document
        env:
          tidy_c: ${{ secrets.TIDY_C_API_KEY }}
        run: |
         Rscript -e 'rmarkdown::render("hw6.Rmd")'
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
